// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/runetale/runevision/handler"
	"github.com/runetale/runevision/interactor"
	"github.com/runetale/runevision/interfaces"
	"github.com/runetale/runevision/repository"
)

// Injectors from wire.go:

func InitializeDashboardHandler(db interfaces.SQLExecuter) interfaces.DashboardHandler {
	dashboardRepository := repository.NewDashboardRepository(db)
	dashboardInteractor := interactor.NewDashboardInteractor(dashboardRepository)
	dashboardHandler := handler.NewDashboardHandler(dashboardInteractor)
	return dashboardHandler
}

// wire.go:

var wireSet = wire.NewSet(handler.WireSet, interactor.WireSet, repository.WireSet)
